# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swayter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Alamofire'

  # Firebase Pods
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  
  # Facebook Pods
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  pod 'FacebookCore'
  

  target 'SwayterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwayterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
